#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
HEADER_NAME="X-Served-By"
HEADER_VALUE=$(hostname)
sudo sed -i "s|# add_header.*|add_header $HEADER_NAME $HEADER_VALUE;|" /etc/nginx/nginx.conf
sudo service nginx start
