#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update -y
apt-get -y install haproxy=2.0.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 144222-web-01 54.144.136.246 check
   server 144222-web-02 54.208.44.210 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
